### ISSUE TITLE
Service broker app crashing

### ISSUE THREAD

**Issue by discoverkr77** [emccode/ecs-cf-service-broker#34]
I pushed the service broker and added the environment variables, but the app keeps crashing with the following error. Wondering if I am missing any settings. Appreciate any help.

Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR java.lang.reflect.InvocationTargetException
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at java.lang.reflect.Method.invoke(Method.java:497)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at java.lang.Thread.run(Thread.java:745)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'serviceInstanceBindingController' defined in URL [jar:file:/home/vcap/app/lib/spring-cloud-cloudfoundry-service-broker-1.0.0.BUILD-SNAPSHOT.jar!/org/springframework/cloud/servicebroker/controller/ServiceInstanceBindingController.class]: Unsatisfied dependency expressed through constructor argument with index 1 of type [org.springframework.cloud.servicebroker.service.ServiceInstanceBindingService]: : Error creating bean with name 'ecsServiceInstanceBindingService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.emc.ecs.serviceBroker.EcsService com.emc.ecs.serviceBroker.service.EcsServiceInstanceBindingService.ecs; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ecsService': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: "segments" parameter is null.; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ecsServiceInstanceBindingService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.emc.ecs.serviceBroker.EcsService com.emc.ecs.serviceBroker.service.EcsServiceInstanceBindingService.ecs; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ecsService': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: "segments" parameter is null.
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:764)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:357)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.boot.SpringApplication.run(SpringApplication.java:1124)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.boot.SpringApplication.run(SpringApplication.java:1113)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at com.emc.ecs.serviceBroker.config.Application.main(Application.java:34)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR ... 6 more
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ecsServiceInstanceBindingService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.emc.ecs.serviceBroker.EcsService com.emc.ecs.serviceBroker.service.EcsServiceInstanceBindingService.ecs; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ecsService': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: "segments" parameter is null.
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR ... 25 more
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.emc.ecs.serviceBroker.EcsService com.emc.ecs.serviceBroker.service.EcsServiceInstanceBindingService.ecs; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ecsService': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: "segments" parameter is null.
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:573)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR ... 37 more
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ecsService': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: "segments" parameter is null.
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
Fri Apr 22 2016 12:43:16 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192)
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116)
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545)
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR ... 39 more
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR Caused by: java.lang.IllegalArgumentException: "segments" parameter is null.
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR at org.glassfish.jersey.uri.internal.JerseyUriBuilder.appendPath(JerseyUriBuilder.java:732)
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR at org.glassfish.jersey.uri.internal.JerseyUriBuilder.appendPath(JerseyUriBuilder.java:727)
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR at org.glassfish.jersey.uri.internal.JerseyUriBuilder.path(JerseyUriBuilder.java:357)
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR at org.glassfish.jersey.uri.internal.JerseyUriBuilder.path(JerseyUriBuilder.java:72)
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR at javax.ws.rs.core.UriBuilder.fromPath(UriBuilder.java:112)
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR at com.emc.ecs.managementClient.Connection.getUriBuilder(Connection.java:144)
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR at com.emc.ecs.managementClient.BaseUrlAction.list(BaseUrlAction.java:17)
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR at com.emc.ecs.serviceBroker.EcsService.lookupObjectEndpoints(EcsService.java:64)
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR at com.emc.ecs.serviceBroker.EcsService.initialize(EcsService.java:54)
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR at java.lang.reflect.Method.invoke(Method.java:497)
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354)
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:305)
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
Fri Apr 22 2016 12:43:17 GMT-0500 (CDT) [APP] ERR ... 51 more

**Comment by spiegela** [comment]
This error is basically stating that the `managementEndpoint` configuration parameter is `null` or not a valid URI.  It's probably a result of the `spring.active.profile` not being set properly.  Are you running this from your IDE or from the command line?

For example, I use the following to start from the command line:
```
./gradlew bootRun
```

FYI.  I've just noticed a bug in the Gradle config that overrides this, and forces the `production` profile unless you're running from the IDE.  I'll submit a PR to fix this directly.

**Comment by discoverkr77** [comment]
thanks for the fix.

**Comment by spiegela** [comment]
@codenrhoden Do you want to give a look prior to merging?

**Comment by spiegela** [comment]
@discoverkr77 Just want to check in.  Based on our conversation, I can close, yes?

Thanks!

**Comment by discoverkr77** [comment]
Yes, I confirm that the issue can be closed. Appreciate all the help.

-Kiran
