### ISSUE TITLE
Restrict bucket create/delete rights to binding users

### ISSUE THREAD

**Issue by spiegela** [emccode/ecs-cf-service-broker#49]
Currently bucket bindings (ECS object users) give the user access to create/remove buckets, which don't fall under the same quota, or could have _no quota at all_.

When creating bucket bindings, the object-user should not have rights to create or delete buckets through the S3 API.

**Comment by discoverkr77** [comment]
@spiegela - I would treat this as a bug and as such +1 on this.

**Comment by spiegela** [comment]
Sounds good. I'm making good progress on #42, I'll start this next.

**Comment by spiegela** [comment]
investigating...

**Comment by spiegela** [comment]
@kravell It turns out that this is a limitation of ECS at the moment.  I've sent an email asking for some details about how this affects your project, so that I can get this in the hands of the ECS product team.
