### ISSUE TITLE
Unable to create bucket with quota

### ISSUE THREAD

**Issue by spiegela** [emccode/ecs-cf-service-broker#65]
Reported by @NavleenKaur-24

```shell-session
$ cf create-service ecs-bucket 5gb testbucket
Creating service instance testbucket in org sds / space dev as aaron.spiegel@emc.com...
FAILED
Server error, status code: 502, error code: 10001, message: Service broker error: java.lang.NullPointerException
```

Problem only exhibits with quota carrying plans.

**Comment by spiegela** [comment]
@NavleenKaur-24  I discovered the issue upon troubleshooting.  The `application.yml` was mis-configured the project.  The `warning` keyword in the plan should have actually been `warn`.  There is a PR in process to fix the `application.yml` and I will open a new issue for making this error message more intelligent.

**Comment by NavleenKaur-24** [comment]
@spiegela Yea sure thanks :)
